version: "3.9"

services:
  homeassistant:
    container_name: homeassistant
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/London
