version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8888:80/tcp"
    environment:
      FTLCONF_webserver_api_password: ''
      TZ: 'America/Chicago'
      PIHOLE_DNS_: 192.168.68.1;1.1.1.1 # or any custom dns
      DNSSEC: 'false'
      WEBTHEME: default-dark
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
