services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: admin # Amend it
      RABBITMQ_DEFAULT_PASS: admin # Amend it
      RABBITMQ_NODENAME: rabbit@rabbitmq   # Explicit node name
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: