http_port 3128

acl localnet src all
http_access allow localnet

# Exclude local domain
acl localdomain dstdomain 
always_direct allow localdomain
never_direct deny localdomain

cache_mem 2048 MB
maximum_object_size 2048 MB
cache_dir ufs /var/spool/squid 1000 16 256

logformat readable %{%Y-%m-%d %H:%M:%S}tl %>a %rm %ru %Hs %<st
access_log /var/log/squid/access.log readable
logfile_rotate 10

# Forward everything else to Privoxy
cache_peer privoxy parent 8118 0 no-query default
never_direct allow all

refresh_pattern ^ftp: 1440 20% 10080
refresh_pattern ^gopher: 1440 0% 1440
refresh_pattern -i (/cgi-bin/|\?) 0 0% 0
refresh_pattern . 0 20% 4320