version: "3.9"
services:
  trilium:
    image: triliumnext/trilium:latest
    container_name: trilium
    ports:
      - "9900:8080"
    volumes:
      - ./trilium-data:/home/node/trilium-data
    environment:
      - TZ=Europe/London
      - TRILIUM_PORT=8080
      - TRILIUM_ADMIN_PASSWORD=admin
    restart: unless-stopped